Repository ivandi1980/new-erapat, pull requests merged in 2020-10, with the labels that each got.

#21 FULLSTACK - Rapat Module
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Controllers/User.php
  app/Helpers/menu_helper.php
  app/Models/RapatModel.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/user/view_user.php
  app/Views/layouts/layout_main.php
  assets/locals/js/jquery-3.5.1.min.js
Labels: enhancement

#22 FULLSTACK - Rapat Module Updated-1
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_helper.php
  app/Models/RapatModel.php
  app/Models/TypeModel.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/user/view_user.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-metro.js
Labels: bug

#23 FULLSTACK - Rapat Module Updated-2
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Models/TypeModel.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-metro.js
Labels: enhancement

#24 BACKEND - Refactor the Auth Login Codes
  app/Config/Filters.php
  app/Config/Routes.php
  app/Controllers/Login.php
  app/Filters/LoginFilter.php
  app/Helpers/navbar_helper.php
  app/Models/Auth_model.php
  app/Models/TypeModel.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/rapat/view_rapat_baru.php
Labels: bug

#26 FRONTEND - input Rapat form refactor
  app/Config/Routes.php
  app/Controllers/Auth.php
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/Riwayat.php
  app/Helpers/menu_helper.php
  app/Helpers/zoom_helper.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: enhancement

#27 FRONTEND - input Rapat form refactor 2
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Controllers/Register.php
  app/Helpers/navbar_helper.php
  app/Helpers/zoom_helper.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
  assets/locals/js/custom-metro.js
Labels: bug, enhancement

#32 GIT - gitignore updated
  .gitignore
Labels: documentation, help wanted

#34 Create Alert for empty upload supporting files
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/User.php
  app/Helpers/alerts_helper.php
  app/Models/RapatModel.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/cpanel/user/view_user.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
  assets/locals/js/custom-metro.js
Labels: enhancement, help wanted

#38 FULLSTACK - Create History Rapat
  app/Config/Routes.php
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/Riwayat.php
  app/Controllers/ZohoConnect.php
  app/Helpers/alerts_helper.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/cpanel/user/view_user.php
  app/Views/cpanel/zoho/view_zoho.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: enhancement, help wanted

#39 FULLSTACK - Create Detail Rapat
  app/Helpers/alerts_helper.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/zoho/view_zoho.php
  assets/locals/css/custom-metro.css
Labels: enhancement, good first issue, help wanted

#43 DATABASE - backup db
  app/Controllers/Pembaharuan.php
  app/Database/sql/rapat.sql
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
Labels: bug

#44 FULLSTACK - Create Riwayat Rapat
  app/Config/Routes.php
  app/Config/Validation.php
  app/Controllers/Riwayat.php
  app/Helpers/alerts_helper.php
  app/Models/RiwayatModel.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
  assets/locals/js/custom-metro.js
Labels: bug, help wanted

#46 FRONTEND - Bug fixing all style
  app/Config/Routes.php
  app/Config/Validation.php
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/Riwayat.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: bug, help wanted

#48 FRONTEND - Bug fixing logged in flow
  app/Config/Routes.php
  app/Controllers/Login.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/auth/view_cek.php
  app/Views/cpanel/auth/view_login.php
  app/Views/errors/response/view_forbidden.php
  app/Views/errors/response/view_not_allowed.php
  app/Views/errors/response/view_not_found.php
  app/Views/errors/response/view_un_authorized .php
  app/Views/errors/response/view_unavailable.php
  app/Views/layouts/layout_main.php
  app/Views/view_calendar.php
  app/Views/view_documentation.php
  assets/locals/css/custom-metro.css
  assets/locals/css/customs-popup.css
  assets/locals/img/favicon.png
  assets/locals/img/loading.gif
  assets/locals/js/custom-metro.js
  captured/login.png
Labels: bug, help wanted

#51 FRONTEND - Bug fixing Navbar child on Detail Page
  app/Config/Routes.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/errors/response/view_forbidden.php
  app/Views/errors/response/view_not_allowed.php
  app/Views/errors/response/view_not_found.php
  app/Views/errors/response/view_un_authorized .php
  app/Views/errors/response/view_unavailable.php
  app/Views/layouts/layout_main.php
  app/Views/view_calendar.php
  assets/locals/img/loading.gif
Labels: bug, help wanted

#52 FULLSTACK - Save Data into Db
  app/Controllers/Rapat.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_helper.php
  app/Models/RapatAddModel.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: bug, enhancement, help wanted

#53 BACKEND - Refactor the Auth by added csrf
  app/Config/Filters.php
  app/Filters/LoginFilter.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/zoom_helper.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/layouts/layout_main.php
Labels: enhancement, help wanted

#57 FULLSTACK - cek offline media meeting
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Models/SubtypeModel.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: bug, enhancement, help wanted

#59 FRONTEND - Fixing Bug Navbar Child
  app/Controllers/Login.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/zoom_helper.php
  app/Views/cpanel/auth/view_cek.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-metro.js
Labels: bug, help wanted, invalid

#61 BACKEND - Hide error by change enviroment
  .htaccess
  captured/calendar_day.png
  captured/calendar_list.png
  captured/calendar_month.png
  captured/calendar_week.png
  captured/dokumentation.png
  captured/login.png
Labels: bug, help wanted

#62 FULLSTACK - erapat form builder
  captured/calendar_day.png
  captured/calendar_list.png
  captured/calendar_month.png
  captured/calendar_week.png
  captured/dokumentation.png
  captured/login.png
Labels: enhancement, help wanted, question

#64 FULLSTACK - Show current offline meeting
  .htaccess
  app/Config/Routes.php
  app/Controllers/Pembaharuan.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-metro.js
Labels: bug, help wanted

#66 FULLSTACK - Reschedulle Rapat
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Helpers/myforms_helper.php
  app/Helpers/navbar_child_helper.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/rapat/view_rapat_reschedulle.php
  app/Views/errors/response/view_forbidden_cancel_meeting.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-tinymce.js
Labels: enhancement, help wanted

#74 FRONTEND - change color tables data
  app/Controllers/Login.php
  app/Controllers/Rapat.php
  app/Database/sql/rapat.sql
  app/Helpers/myforms_helper.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/layouts/layout_main.php
  assets/locals/css/custom-metro.css
Labels: bug, enhancement, help wanted

#76 FULLSTACK - Upload Undangan
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Models/UndanganModel.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/rapat/view_upload_undangan.php
  assets/locals/css/custom-metro.css
  uploads/UNDANGAN_RAPAT.pdf
Labels: enhancement, help wanted

#78 FULLSTACK - Upload Notulen
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_upload_absensi.php
  app/Views/cpanel/rapat/view_upload_notulen.php
  uploads/NOTULENSI_RAPAT.pdf
Labels: enhancement, help wanted

#79 FULLSTACK - Upload Absensi
  app/Controllers/Rapat.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_baru.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/rapat/view_upload_absensi.php
  app/Views/layouts/layout_main.php
  uploads/ABSENSI_RAPAT.pdf
  uploads/ABSENSI_RAPAT_1.pdf
  uploads/ABSENSI_RAPAT_2.pdf
  uploads/ABSENSI_RAPAT_3.pdf
Labels: enhancement, help wanted

#87 FULLSTACK - User Page and All Features
  app/Config/Routes.php
  app/Controllers/User.php
  app/Database/sql/rapat.sql
  app/Models/UserModel.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
  assets/data/profile/2.png
  assets/data/profile/31.png
  assets/data/profile/32.png
  assets/data/profile/33.png
  assets/data/profile/34.png
  assets/data/profile/default-avatar.jpg
  assets/data/profile/default.png
Labels: enhancement, help wanted

#88 FULLSTACK - Create Password and all it functional
  app/Config/Routes.php
  app/Config/Validation.php
  app/Controllers/User.php
  app/Models/UserModel.php
  app/Views/cpanel/user/view_change_password.php
  assets/locals/css/custom-metro.css
Labels: bug, enhancement, help wanted

#89 FRONTEND - Creating Alerts for Uploads
  .htaccess
  app/Config/Routes.php
  app/Controllers/User.php
  app/Helpers/unggah_helper.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
Labels: bug, enhancement, help wanted

#91 FULLSTACK - added status finish when meeting end
  .htaccess
  app/Helpers/myforms_helper.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/view_documentation.php
  assets/locals/css/custom-metro.css
  uploads/ABSENSI_RAPAT.pdf
  uploads/NOTULENSI_RAPAT.pdf
  uploads/UNDANGAN_RAPAT.pdf
Labels: bug, help wanted

#96 FULLSTACK - Create Riwayat/History Online Meeting
  app/Config/Routes.php
  app/Controllers/Riwayat.php
  app/Controllers/User.php
  app/Helpers/myforms_helper.php
  app/Views/cpanel/riwayat/view_offline.php
  app/Views/cpanel/riwayat/view_online.php
  app/Views/cpanel/user/view_user.php
  uploads/UNDANGAN_RAPAT_1.pdf
Labels: bug, enhancement, help wanted

#98 FULLSTACK - create upload tambahan
  2/UNDANGAN_RAPAT.pdf
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/rapat/view_upload_absensi.php
  app/Views/cpanel/rapat/view_upload_tambahan1.php
  app/Views/cpanel/rapat/view_upload_tambahan2.php
  app/Views/cpanel/rapat/view_upload_tambahan3.php
  uploads/ABSENSI_RAPAT.pdf
  uploads/NOTULENSI_RAPAT.pdf
  uploads/UNDANGAN_RAPAT.pdf
  uploads/Und_Kick_off_Meeting_Roadmap_Kerjasama_Balitbang_13_Agustus.pdf
Labels: bug

#100 FULLSTACK - Create Account Module
  1index.html
  2index.html
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/Admin.php
  app/Helpers/menu_helper.php
  app/Models/AccountModel.php
  app/Views/cpanel/account/view_account.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/admin/view_edit_admin.php
Labels: enhancement, invalid

#101 FULLSTACK - Account Refactoring Code 1
  app/Controllers/Account.php
  app/Controllers/Admin.php
  app/Database/sql/rapat.sql
  app/Helpers/menu_helper.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/account/view_account.php
Labels: bug

#102 FULLSTACK - Account Refactoring Code 2
  app/Controllers/Account.php
  app/Controllers/Admin.php
  app/Helpers/menu_helper.php
  app/Views/cpanel/account/view_account.php
Labels: bug

#105 FULLSTACK - Session Login Bugs
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/BaseController.php
  app/Controllers/Login.php
  app/Filters/LoginFilter.php
  app/Models/AccountModel.php
  app/Views/cpanel/account/view_account.php
  app/Views/layouts/layout_main.php
Labels: bug, help wanted, invalid

#107 FULLSTACK - Meeting tables refactor
  app/Config/Filters.php
  app/Controllers/Login.php
  app/Filters/LoginFilter.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_reschedulle.php
  app/Views/cpanel/riwayat/view_riwayat.php
  uploads/UNDANGAN_RAPAT_1.pdf
Labels: bug, help wanted, invalid

#112 BACKEND - Authentication & Authorization Bugs
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/Login.php
  app/Views/cpanel/account/view_account.php
  app/Views/cpanel/account/view_detail_account.php
Labels: bug, help wanted, invalid

#116 FULLSTACK - Login Bugs and add new blokir feature
  app/Controllers/Account.php
  app/Controllers/BaseController.php
  app/Controllers/Login.php
  app/Controllers/User.php
  app/Helpers/menu_helper.php
  app/Models/AuthModel.php
  app/Models/Auth_model.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/layouts/layout_main.php
Labels: bug, enhancement, help wanted, invalid

#118 FULLSTACK - Admin Profile Page's Bugs
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/Admin.php
  app/Controllers/BaseController.php
  app/Controllers/Login.php
  app/Helpers/menu_helper.php
  app/Views/cpanel/account/view_account.php
  app/Views/cpanel/account/view_detail_account.php
  app/Views/cpanel/account/view_edit_account.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/admin/view_edit_admin.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/layouts/layout_main.php
  assets/locals/js/custom-datatable.js
Labels: bug, help wanted, invalid

#120 FULLSTACK - User Profile Page's Bugs
  app/Config/Routes.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Helpers/zoom_helper.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
Labels: bug, help wanted, invalid

#123 BACKEND - Bugs, Change default date views to Indonesian
  .htaccess
  app/Controllers/Account.php
  app/Controllers/Admin.php
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/Riwayat.php
  app/Controllers/User.php
  app/Helpers/tanggal_helper.php
  app/Views/cpanel/account/view_detail_account.php
  app/Views/cpanel/account/view_edit_account.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/admin/view_edit_admin.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/riwayat/view_offline.php
  app/Views/cpanel/riwayat/view_online.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
Labels: bug, enhancement, help wanted, invalid

#124 FRONTEND - Profile & Account Display code refactor
  app/Config/Routes.php
  app/Views/cpanel/account/view_detail_account.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/admin/view_edit_admin.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
  assets/locals/css/custom-metro.css
Labels: bug, enhancement, help wanted, invalid

#126 BACKEND - Update user & account features
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/BaseController.php
  app/Controllers/User.php
  app/Views/cpanel/account/view_access_account.php
  app/Views/cpanel/user/view_change_password.php
Labels: bug, help wanted

#130 FULLSTACK - Sekretariat Codes Part 1
  app/Config/Routes.php
  app/Controllers/Bagian.php
  app/Controllers/Sekretariat.php
  app/Helpers/menu_helper.php
  app/Views/cpanel/bagian/view_bagian.php
  app/Views/cpanel/sekretariat/view_sekretariat.php
Labels: enhancement, help wanted

#131 FULLSTACK - Sekretariat Codes Part 2
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/BaseController.php
  app/Controllers/Department.php
  app/Controllers/Sekretariat.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_helper.php
  app/Models/SekretariatModel.php
  app/Views/cpanel/sekretariat/view_add_sekretariat.php
  app/Views/cpanel/sekretariat/view_edit_sekretariat.php
  app/Views/cpanel/sekretariat/view_sekretariat.php
Labels: enhancement, help wanted

#132 FULLSTACK - Bagian Codes Part 1
  app/Config/Routes.php
  app/Controllers/Bagian.php
  app/Controllers/Sekretariat.php
  app/Helpers/menu_helper.php
  app/Models/SubDepartmentModel.php
  app/Views/cpanel/account/view_account.php
  app/Views/cpanel/bagian/view_add_bagian.php
  app/Views/cpanel/bagian/view_bagian.php
  app/Views/cpanel/bagian/view_edit_bagian.php
Labels: enhancement, help wanted

#133 FULLSTACK - Bugfixing module bagian
  app/Controllers/Bagian.php
  app/Helpers/navbar_child_helper.php
  app/Models/SubDepartmentModel.php
  app/Views/cpanel/bagian/view_edit_bagian.php
Labels: bug, help wanted, invalid

#134 FULLSTACK - Bagian Codes Part 2
  app/Controllers/Bagian.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/bagian/view_bagian.php
  app/Views/cpanel/bagian/view_edit_bagian.php
Labels: bug, help wanted, invalid

#136 FULLSTACK - Zoom Array Offset of Null
  app/Config/Routes.php
  app/Controllers/BaseController.php
  app/Controllers/Zoom.php
  app/Database/sql/rapat.sql
  app/Helpers/menu_helper.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Models/ZoomModel.php
  app/Models/ZoomsModel.php
  app/Views/cpanel/zoom/view_add_zoom.php
  app/Views/cpanel/zoom/view_edit_zoom.php
  app/Views/cpanel/zoom/view_zoom.php
Labels: bug

#138 FULLSTACK - Account bugfix
  app/Config/Routes.php
  app/Controllers/Account.php
  app/Controllers/Zoom.php
  app/Database/sql/rapat.sql
  app/Models/ZoomsModel.php
  app/Views/cpanel/zoom/view_add_zoom.php
  app/Views/cpanel/zoom/view_zoom.php
Labels: bug, help wanted, invalid

#140 FRONTEND - Main Menu not show on Rapat New Input Form
  app/Helpers/navbar_helper.php
Labels: bug, help wanted, invalid

#142 FULLSTACK - Download Files Supported Helper
  app/Config/Routes.php
  app/Config/Validation.php
  app/Controllers/Account.php
  app/Controllers/Rapat.php
  app/Helpers/download_helper.php
  app/Views/cpanel/account/view_add_account.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/rapat/view_upload_tambahan1.php
  app/Views/cpanel/rapat/view_upload_tambahan2.php
  app/Views/cpanel/rapat/view_upload_tambahan3.php
  uploads/upload_1.pdf
  uploads/upload_2.pdf
  uploads/upload_3.pdf
Labels: bug, help wanted, invalid

#143 FULLSTACK - Download Files Supported Helper part2
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  uploads/upload_tambahan_1.pdf
  uploads/upload_tambahan_2.pdf
  uploads/upload_tambahan_3.pdf
Labels: bug, help wanted, invalid

#146 FULLSTACK - BUGS Offline Meeting not shown on rapat pages
  app/Controllers/BaseController.php
  app/Controllers/Pembaharuan.php
  app/Controllers/Rapat.php
  app/Controllers/Riwayat.php
  app/Database/sql/rapat.sql
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Helpers/tanggal_helper.php
  app/Helpers/zoom_helper.php
  app/Models/AllRapatModel.php
  app/Models/RapatOnOffModel.php
  app/Models/RapatStatusModel.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/rapat/view_rapat.php
  app/Views/cpanel/rapat/view_rapat_edit.php
  app/Views/cpanel/rapat/view_rapat_reschedulle.php
  app/Views/cpanel/riwayat/view_offline.php
  app/Views/cpanel/riwayat/view_online.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/errors/response/view_forbidden_cancel_meeting_edit.php
  app/Views/errors/response/view_forbidden_cancel_meeting_reschedulle.php
Labels: bug, help wanted, invalid

#148 FRONTEND - BUGS Calendar Bugs showing offline meeting
  app/Controllers/Pembaharuan.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
Labels: bug, help wanted, invalid

#151 FRONTEND - BUG fixing date
  app/Controllers/Main.php
  app/Views/cpanel/account/view_access_account.php
  app/Views/cpanel/account/view_add_account.php
  app/Views/cpanel/account/view_change_password.php
  app/Views/cpanel/account/view_detail_account.php
  app/Views/cpanel/account/view_edit_account.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/admin/view_change_password.php
  app/Views/cpanel/admin/view_edit_admin.php
  app/Views/cpanel/bagian/view_add_bagian.php
  app/Views/cpanel/bagian/view_edit_bagian.php
  app/Views/cpanel/pembaharuan/view_cekoffline.php
  app/Views/cpanel/pembaharuan/view_cekzoom.php
  app/Views/cpanel/pembaharuan/view_pembaharuan.php
  app/Views/cpanel/riwayat/view_offline.php
  app/Views/cpanel/riwayat/view_online.php
  app/Views/cpanel/riwayat/view_riwayat.php
  app/Views/cpanel/sekretariat/view_add_sekretariat.php
  app/Views/cpanel/sekretariat/view_edit_sekretariat.php
  app/Views/view_main.php
Labels: bug, help wanted, invalid

#152 FRONTEND - BUG fixed date part 2
  app/Views/cpanel/rapat/view_rapat_detail.php
  app/Views/cpanel/user/view_change_password.php
  app/Views/cpanel/user/view_edit_user.php
  app/Views/cpanel/user/view_user.php
Labels: bug, help wanted

#154 BACKEND - BUGS Download files
  app/Controllers/Rapat.php
  app/Controllers/User.php
  app/Controllers/Zoom.php
  uploads/upload_1.pdf
  uploads/upload_2.pdf
  uploads/upload_3.pdf
  uploads/upload_tambahan_1.pdf
  uploads/upload_tambahan_2.pdf
  uploads/upload_tambahan_3.pdf
Labels: bug, help wanted, invalid

#156 BACKEND - added TCPDF library for creating pdf
  composer.json
  composer.lock
  uploads/upload_1.pdf
  uploads/upload_2.pdf
  uploads/upload_3.pdf
  uploads/upload_tambahan_1.pdf
  uploads/upload_tambahan_2.pdf
  uploads/upload_tambahan_3.pdf
Labels: enhancement, help wanted

#157 FULLSTACK - Cetak Module Created
  app/Config/Routes.php
  app/Controllers/Cetak.php
  app/Controllers/Riwayat.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_child_helper.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/cetak/view_cetak.php
Labels: enhancement, help wanted, invalid

#160 FULLSTACK - modul cetak
  app/Controllers/Cetak.php
  app/Views/cpanel/cetak/view_cetak.php
  assets/locals/css/custom-metro.css
Labels: bug, help wanted, invalid

#165 FULLSTACK - Create Cetak Detail PDF
  app/Config/Autoload.php
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Views/cpanel/rapat/view_cetak_detail.php
  app/Views/cpanel/rapat/view_rapat_detail.php
  assets/locals/img/header.png
  composer.json
  composer.lock
Labels: enhancement, help wanted, invalid

#166 FULLSTACK - Cetak Table data based on date
  app/Config/Routes.php
  app/Controllers/Rapat.php
  app/Views/cpanel/cetak/view_cetak.php
  app/Views/cpanel/rapat/view_cetak_detail.php
  app/Views/cpanel/rapat/view_cetak_perdate.php
Labels: enhancement, help wanted
