Repository ivandi1980/new-erapat, pull requests merged in 2020-09, with the labels that each got.

#10 FRONTEND - Refactor Codebase-3
  README.md
  app/Controllers/Auth.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/auth/view_register.php
  app/Views/layouts/layout_main.php
  captured/calendar_day.png
  captured/calendar_list.png
  captured/calendar_month.png
  captured/calendar_week.png
  captured/dokumentasi.png
  captured/login.png
  public/assets/locals/css/custom-metro.css
  public/assets/locals/img/perhub.svg
  public/assets/locals/img/zoho.svg
Labels: enhancement

#11 FRONTEND - Refactor Codebase-4
  app/Controllers/Auth.php
  app/Controllers/BaseController.php
  app/Controllers/Department.php
  app/Controllers/ZohoConnect.php
  app/Database/sql/rapat.sql
  app/Helpers/navbar_helper.php
  app/Models/DepartmentModel.php
  app/Models/UserModel.php
  app/Views/cpanel/auth/view_login.php
  app/Views/cpanel/auth/view_register.php
  app/Views/errors/response/view_forbidden.php
  app/Views/errors/response/view_not_allowed.php
  app/Views/errors/response/view_not_found.php
  app/Views/errors/response/view_un_authorized .php
  app/Views/errors/response/view_unavailable.php
  app/Views/layouts/layout_main.php
  captured/calendar_day.png
  captured/calendar_list.png
  captured/calendar_month.png
  captured/calendar_week.png
  captured/dokumentasi.png
  captured/login.png
  public/assets/locals/css/custom-metro.css
Labels: enhancement

#12 FRONTEND - remove public folder & all it's components
  .htaccess
  app/Config/App.php
  assets/locals/css/custom-metro.css
  assets/locals/img/perhub.svg
  assets/locals/img/transport.svg
  assets/locals/img/zoho.svg
  favicon.ico
  index.php
  robots.txt
Labels: enhancement

#13 FRONTEND - login refactor
  app/Config/Routes.php
  app/Controllers/Auth.php
  app/Views/cpanel/auth/view_login.php
  assets/locals/css/custom-metro.css
  captured/login.png
Labels: help wanted

#14 FULLSTACK - Auth-Focus Code
  NULL/ci_session1b1o8j92f1i6cqmjo6pdvo5qglu4sg0u
  NULL/ci_session1kf8q7ndhop7m4bjlr2rv56g4g17tjb3
  NULL/ci_session43n7bkorjpnn9t91o0m285hrcrtb4ovb
  NULL/ci_session4nbu25pn8n9eumf5v60nrgt3ijmh75lc
  NULL/ci_session7n7f95ta20jk2slvu5b8ib2itl1j6hgd
  NULL/ci_sessionanfrgr40t7u7nuqk7ena322u3jdc6f24
  NULL/ci_sessionbfm1gh7ol7gtaaivi2849drgtnbeheuj
  NULL/ci_sessionqljhq0045j3de9ftgpskt3prf7h43u87
  NULL/ci_sessionvvebimf89q4ru5dfha5qabpcrk0ocd4e
  app/Controllers/Auth.php
  app/Models/UserModel.php
  app/Views/cpanel/auth/view_login.php
  app/Views/view_main.php
  assets/locals/css/custom-metro.css
Labels: enhancement

#15 BACKEND - Creating Admin Module
  .gitignore
  NULL/ci_session1b1o8j92f1i6cqmjo6pdvo5qglu4sg0u
  NULL/ci_session1kf8q7ndhop7m4bjlr2rv56g4g17tjb3
  NULL/ci_session43n7bkorjpnn9t91o0m285hrcrtb4ovb
  NULL/ci_session4nbu25pn8n9eumf5v60nrgt3ijmh75lc
  NULL/ci_session7n7f95ta20jk2slvu5b8ib2itl1j6hgd
  NULL/ci_sessionanfrgr40t7u7nuqk7ena322u3jdc6f24
  NULL/ci_sessionbfm1gh7ol7gtaaivi2849drgtnbeheuj
  NULL/ci_sessionqljhq0045j3de9ftgpskt3prf7h43u87
  NULL/ci_sessionvvebimf89q4ru5dfha5qabpcrk0ocd4e
  app/Config/Routes.php
  app/Controllers/Admin.php
  app/Controllers/Auth.php
  app/Views/cpanel/admin/view_admin.php
Labels: enhancement

#16 BACKEND - Updating Admin Module
  NULL/ci_sessionqljhq0045j3de9ftgpskt3prf7h43u87
  app/Config/App.php
  app/Config/Database.php
  app/Config/Routes.php
  app/Controllers/Admin.php
  app/Controllers/Auth.php
  app/Helpers/navbar_helper.php
  app/Views/cpanel/admin/view_admin.php
  app/Views/cpanel/auth/view_login.php
  assets/locals/css/custom-metro.css
Labels: enhancement

#17 MASTER - Updating Readme & Screenshoots
  README.md
  captured/calendar_day.png
  captured/calendar_list.png
  captured/calendar_month.png
  captured/calendar_week.png
  captured/dokumentasi.png
  captured/dokumentation.png
  captured/login.png
Labels: documentation

#20 FULLSTACK - User Module
  app/Controllers/Admin.php
  app/Controllers/Auth.php
  app/Controllers/User.php
  app/Helpers/alerts_helper.php
  app/Helpers/menu_helper.php
  app/Helpers/navbar_helper.php
  app/Models/MeetingModel.php
  app/Views/cpanel/user/view_user.php
  assets/data/profile/2.png
  assets/data/profile/31.png
  assets/data/profile/32.png
  assets/data/profile/33.png
  assets/data/profile/34.png
  assets/data/profile/default-avatar.jpg
  assets/locals/css/custom-metro.css
Labels: bug, duplicate
